collections:
  rails:
    output: true

defaults:
  - scope:
      path: ""
      type: "rails"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
theme: minima